### PR TITLE
ssh: explicitly set ~ for home directory unless using cmd.exe

### LINKED ISSUE #16568: coder_agent dir property breaks Mutagen file sync from Windows
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

[Mutagen] fails to install it's agent on a Coder workspace were the `dir` property is set.  For example, our Write Coder on Coder template uses:

```
resource "coder_agent" "dev" {
  arch = "amd64"
  os   = "linux"
  dir  = local.repo_dir
  env = {
    OIDC_TOKEN : data.coder_workspace_owner.me.oidc_access_token,
  }
  startup_script_behavior = "blocking"

  ...
  }
```

Mutagen works by `scp`'ing an agent file, then chmod'ing the file and executing it over SSH.

`scp` defaults to the user's home directory as the place to start any relative paths for `scp`. So the agent binary gets copied to `~/mutagen-agent<some UUID>`. However, because we set `dir` in the terraform template, the default working directory for SSH is not the home directory, and so the SSH commands cannot locate the mutagen agent file.

Essentially this issue arises because Mutagen assumes `scp` and `ssh` will default to the home directory, or at least the same directory, but we break this assumption for SSH.

Options to fix: 

1. Change our SSH server to also default scp to the `dir` path by default.
  a. note that successful install moves the binary and doesn't leave the file in the `dir` directory, unless there is a failure

2. Patch mutagen so that it uses explicit paths

### Relevant Log Output

```shell
C:\Users\micha\mut\mut-dg> mutagen sync create --name=mut-dg . coder@mut-dg.coder:1:~/repos/coder
Setting agent executability...
Error: unable to connect to beta: unable to connect to endpoint: unable to dial agent endpoint: unable to install agent: unable to set agent executability: remote error: chmod: cannot access '.mutagen-agentf0875a2b-f7c7-401a-a799-e36178f5fa5b': No such file or directory
```

### Expected Behavior

Mutagen copies its agent over and is able to file sync.

### Steps to Reproduce

1. Install Mutagen
2. Install Coder Desktop or run `coder config-ssh` to get SSH working with your workspace
3. Push or use a template that sets the `dir` property on `coder_agent` to something other than the home directory
4. Create a file sync with the workspace using Mutagen

### Environment

- Host OS: Windows 11
- Coder version: Coder v2.18.4+6125358

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by spikecurtis**
Fixes https://github.com/coder/coder/issues/16568

This PR uses an explicit `~` in SSH paths to ensure that the mutagen agent is installed in the home directory, even when the SSH default directory is some other directory, as is the case for some Coder workspaces.

Note that this breaks the Docker transport on Linux, since the Docker transport also sets the explicit home directory. If we ever wanted to upstream this, we would need a better fix, but for Coder's purposes we are only interested in SSH-based file sync.

The problem is that while mutagen defines a `Transport` interface, the abstraction is very leaky: in the case of Docker, mutagen actively probes the endpoint to figure out the home directory, and then adds it under the covers. In the case of SSH, mutagen assumes (incorrectly in Coder's case) that the default directory is the home directory. The implementations also differ in how they handle different operating systems, with Docker using probing, while SSH depends on the calling function to retry with different requests that might succeed on different operating systems.

For now, I just don't think it's worth making a proper fix that refactors the use of the `Transport` interface, given that we don't care about Docker support. I [raised an issue on the main mutagen repo](https://github.com/mutagen-io/mutagen/issues/521) asking if they would consider an PR and got no answer. While the repository is still getting some maintenance, it mainly consists of dependency updates. I don't think the team is able to devote time to considering a larger fix for us.

### CODE REVIEW

File: pkg/agent/dial.go [hunk 1]
```diff
@@ -4,6 +4,7 @@ import (
 	"bytes"
 	"errors"
 	"fmt"
+	"github.com/mutagen-io/mutagen/pkg/prompting"
```
Comment (deansheather) [inline pkg/agent/dial.go]: Import formatting

File: pkg/agent/dial.go [hunk 2]
```diff
@@ -176,6 +144,49 @@ func connect(logger *logging.Logger, transport Transport, mode, prompter string,
...
+	if mutagen.DevelopmentModeEnabled {
+		dataDirectoryName = filesystem.MutagenDataDirectoryDevelopmentName
+	}
+	pathComponents = append(pathComponents,
+		dataDirectoryName,
+		filesystem.MutagenAgentsDirectoryName,
+		mutagen.Version,
+		BaseName,
+	)
+	return strings.Join(pathComponents, pathSeparator)
```
Comment (deansheather) [inline pkg/agent/dial.go]: Most of this could probably be moved into (another) new function like `remoteHomePath(cmdExe bool, components ...string)` so it could be used from both here and `install.go`

File: pkg/process/errors.go [hunk 3]
```diff
@@ -20,6 +20,10 @@ const (
 	// windowsCommandNotFoundFragment is a fragment of the error output returned
 	// on Windows systems when a command cannot be found.
 	windowsCommandNotFoundFragment = "The system cannot find the path specified"
+	// windowsPowershellCommandNotFoundFragment is a fragment of the error output
+	// returned on Windows systems running Powershell when a command cannot be
+	// found.
+	windowsPowershellCommandNotFoundFragment = "is not recognized as the name of a cmdlet, function, script file, or operable program."
```
Comment (deansheather) [inline pkg/process/errors.go:26]: This seems like it would break if you have a different OS language, but I guess mutagen was already doing similar error string checks previously and I can't really think of a better way to accomplish this. So it's probably fine for now

**Review by deansheather — APPROVED** [review]
Seems reasonable. I guess Mutagen doesn't have a great cmd/powershell test suite?

**Review by ethanndickson — APPROVED** [review]
