### PR TITLE
fix: use a more generic powershell error fragment for Windows probing

### LINKED ISSUE #566: Coder Desktop File Sync does not work against Windows workspaces
This is an upstream (Mutagen) issue. Not sure if it effects all Windows workspaces, or just the `Windows Web RDP` template I tried it against. Either way, we'll likely need to fix it on our fork.

Latest Mutagen release:
```
~/D/mutagen_darwin_arm64_v0.18.1 2 » ./mutagen sync create ~/Music/ "windows.coder:C:\Users\Default\Desktop"
Started Mutagen daemon in background (terminate with "mutagen daemon stop")
Connecting to agent (POSIX)...
Error: unable to connect to beta: unable to connect to endpoint: unable to dial agent endpoint: unable to handshake with agent process: unable to receive server magic number: EOF (error output: ^[[31;1m.mutagen/agents/0.18.1/mutagen-agent: ^[[31;1mThe term '.mutagen/agents/0.18.1/mutagen-agent' is not recognized as a name of a cmdlet, function, script file, or executable program.^[[0m\r
^[[31;1m^[[31;1mCheck the spelling of the name, or if a path was included, verify that the path is correct and try again.^[[0m)
```

Our fork:
```
/A/C/C/C/Resources » MUTAGEN_DATA_DIRECTORY="/Users/ethan/Library/Application Support/Coder Desktop/Mutagen" ./mutagen-darwin-arm64 sync create ~/Music/ "windows.coder:C:\Users\Default\Desktop"
Connecting to agent (POSIX)...
Error: unable to connect to beta: unable to connect to endpoint: unable to dial agent endpoint: unable to handshake with agent process: unable to receive server magic number: EOF (error output: ^[[31;1m~/.mutagen/agents/0.18.1/mutagen-agent: ^[[31;1mThe term '~/.mutagen/agents/0.18.1/mutagen-agent' is not recognized as a name of a cmdlet, function, script file, or executable program.^[[0m\r
^[[31;1m^[[31;1mCheck the spelling of the name, or if a path was included, verify that the path is correct and try again.^[[0m)
```

I discovered this in the macOS UI, where the user at least sees an error message in the meantime:

Image

### PR DESCRIPTION
**Pull request by ethanndickson**
Closes https://github.com/coder/internal/issues/566

Very very funny to me that someone at Microsoft changed this error message, especially the "a name" <=> "the name".

File sync working:
image

### CODE REVIEW

**Comment by ethanndickson** [comment]
* **#2** <a href="https://app.graphite.dev/github/pr/coder/mutagen/2?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/coder/mutagen/2?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by deansheather — APPROVED** [review]

**Review by spikecurtis — APPROVED** [review]

**Comment by ethanndickson** [comment]
### Merge activity

* **Apr 14, 3:55 AM EDT**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/coder/mutagen/2).
* **Apr 14, 3:55 AM EDT**: A user merged this pull request with [Graphite](https://app.graphite.dev/github/pr/coder/mutagen/2).

File: pkg/process/errors.go [hunk 1]
```diff
@@ -23,7 +23,10 @@ const (
 	// windowsPowershellCommandNotFoundFragment is a fragment of the error output
 	// returned on Windows systems running Powershell when a command cannot be
 	// found.
-	windowsPowershellCommandNotFoundFragment = "is not recognized as the name of a cmdlet, function, script file, or operable program."
+	// Different Windows versions use slightly error messages.
```
Comment (matifali) [inline pkg/process/errors.go:26]:
```suggestion
	// Different Windows versions use slightly different error messages.
```
